---
- name: spark
  hosts: master 
  gather_facts: no

  vars:
    ansible_become_pass: "ccma"

  tasks:
    - name: Copy .yml files to k8s master
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: ccma
        group: ccma
      with_items:
        - { src: "nginx.yml", dest: "/home/ccma/nginx.yml" }
        - { src: "spark-master.yml", dest: "/home/ccma/spark-master.yml" }
        - { src: "spark-master-service.yml", dest: "/home/ccma/spark-master-service.yml" }    
        - { src: "spark-worker.yml", dest: "/home/ccma/spark-worker.yml" }

    # Spark image
    - name: Download Spark binary file
      get_url:
        url: http://ftp.tc.edu.tw/pub/Apache/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz
        dest: /home/ccma/spark-2.3.1-bin-hadoop2.7.tgz
        mode: 0440

    - name: Extract Spark file
      become: yes
      unarchive:
        src: /home/ccma/spark-2.3.1-bin-hadoop2.7.tgz
        dest: /usr/local
        remote_src: yes

    - name: Add Spark symlink
      become: yes
      file:
        state: link
        src: /usr/local/spark-2.3.1-bin-hadoop2.7
        dest: /usr/local/spark

    - name: Set Spark Home
      become: yes
      lineinfile:
        dest: /etc/environment
        regexp: ^.*(SPARK_HOME).*$
        line: SPARK_HOME=/usr/local/spark
      register: spark_home

    - name: Debug spark_home
      debug:
        var: spark_home

    - name: Set Spark Path
      lineinfile:
        dest: ~/.bashrc
        regexp: ^.*(\$+SPARK_HOME).*$
        line: export PATH=$PATH:$SPARK_HOME/bin
      register: spark_path

    - name: Debug spark_path
      debug:
        var: spark_path

    - name: Clean downloaded package
      file:
        state: absent
        path: /home/ccma/spark-2.3.1-bin-hadoop2.7.tgz

    - name: Build Spark Docker image using docker-image-tool.sh
      shell: "./bin/docker-image-tool.sh -r ccma -t latest build"
      args: 
        chdir: /usr/local/spark/
      register: build_spark_image

    - name: Debug build_spark_image
      debug:
        var: build_spark_image

    # nginx
    - name: Create an nginx deployment
      shell: "kubectl create -f nginx.yml"
      args:
        chdir: /home/ccma
      register: create_nginx

    - name: Debug create_nginx
      debug:
        var: create_nginx

    # Spark
    - name: Create a spark-master deployment
      shell: "kubectl create -f spark-master.yml"
      args:
        chdir: /home/ccma
      register: create_spark_master

    - name: Debug create_spark_master
      debug:
        var: create_spark_master

    - name: Create a spark-master service
      shell: "kubectl create -f spark-master-service.yml"
      args:
        chdir: /home/ccma
      register: create_spark_master_svc

    - name: Debug create_spark_master_svc
      debug:
        var: create_spark_master_svc

    - name: Create a spark-worker deployment
      shell: "kubectl create -f spark-worker.yml"
      args:
        chdir: /home/ccma
      register: create_spark_worker

    - name: Debug create_spark_worker
      debug:
        var: create_spark_worker
