---
apiVersion: v1
kind: service
metadata:
  name: spark-master
  labels:
    name: spark-master
spec:
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
  - name: spark
    port: 7077
    targetPort: 7077
  selector:
    name: spark-master
